// assets/skeleton-elements/react/esm/SkeletonImage.js
function _extends() { _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; }; return _extends.apply(this, arguments); }

function _objectWithoutPropertiesLoose(source, excluded) { if (source == null) return {}; var target = {}; var sourceKeys = Object.keys(source); var key, i; for (i = 0; i < sourceKeys.length; i++) { key = sourceKeys[i]; if (excluded.indexOf(key) >= 0) continue; target[key] = source[key]; } return target; }

import React from 'react';
import multiplySvgPoints from './multiply-svg-points';

var SkeletonImage = function SkeletonImage(_temp) {
  var _ref = _temp === void 0 ? {} : _temp,
      _ref$tag = _ref.tag,
      Tag = _ref$tag === void 0 ? 'span' : _ref$tag,
      _ref$width = _ref.width,
      width = _ref$width === void 0 ? 1200 : _ref$width,
      _ref$height = _ref.height,
      height = _ref$height === void 0 ? 600 : _ref$height,
      borderRadius = _ref.borderRadius,
      color = _ref.color,
      iconColor = _ref.iconColor,
      _ref$showIcon = _ref.showIcon,
      showIcon = _ref$showIcon === void 0 ? true : _ref$showIcon,
      effect = _ref.effect,
      className = _ref.className,
      children = _ref.children,
      other = _objectWithoutPropertiesLoose(_ref, ["tag", "width", "height", "borderRadius", "color", "iconColor", "showIcon", "effect", "className", "children"]);

  var skeletonClassName = ['skeleton-image', effect && "skeleton-effect-" + effect, className].filter(function (c) {
    return !!c;
  }).join(' ');

  function multiplyPoints(pointsString) {
    return multiplySvgPoints(pointsString, 56, width, height);
  }

  return /*#__PURE__*/React.createElement(Tag, _extends({
    className: skeletonClassName
  }, other), /*#__PURE__*/React.createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    width: width,
    height: height,
    viewBox: "0 0 " + width + " " + height,
    style: {
      borderRadius: borderRadius
    },
    preserveAspectRatio: "none"
  }, /*#__PURE__*/React.createElement("polygon", {
    style: {
      fill: color
    },
    fillRule: "evenodd",
    points: "0 0 " + width + " 0 " + width + " " + height + " 0 " + height
  }), showIcon && /*#__PURE__*/React.createElement("path", {
    style: {
      fill: iconColor
    },
    d: multiplyPoints('M7.7148,49.5742 L48.2852,49.5742 C53.1836,49.5742 55.6446,47.1367 55.6446,42.3086 L55.6446,13.6914 C55.6446,8.8633 53.1836,6.4258 48.2852,6.4258 L7.7148,6.4258 C2.8398,6.4258 0.3554,8.8398 0.3554,13.6914 L0.3554,42.3086 C0.3554,47.1602 2.8398,49.5742 7.7148,49.5742 Z M39.2851,27.9414 C38.2304,27.0039 37.0351,26.5118 35.7695,26.5118 C34.457,26.5118 33.3085,26.9571 32.2304,27.918 L21.6366,37.3867 L17.3007,33.4492 C16.3163,32.582 15.2617,32.1133 14.1366,32.1133 C13.1054,32.1133 12.0976,32.5586 11.1366,33.4258 L4.1288,39.7305 L4.1288,13.8789 C4.1288,11.4414 5.4413,10.1992 7.7851,10.1992 L48.2147,10.1992 C50.535,10.1992 51.8708,11.4414 51.8708,13.8789 L51.8708,39.7539 L39.2851,27.9414 Z M17.8163,28.1992 C20.8398,28.1992 23.3241,25.7149 23.3241,22.668 C23.3241,19.6445 20.8398,17.1367 17.8163,17.1367 C14.7695,17.1367 12.2851,19.6445 12.2851,22.668 C12.2851,25.7149 14.7695,28.1992 17.8163,28.1992 Z')
  })), children);
};

export default SkeletonImage;

// assets/skeleton-elements/angular/esm2015/lib/skeleton-image.js
import { Component, Input } from '@angular/core';
import { multiplySvgPointsService } from './multiply-svg-points';
export class SkeletonImageComponent {
    constructor() {
        this.width = 1200;
        this.height = 600;
        this.showIcon = true;
    }
    multiplyPoints(pointsString) {
        return multiplySvgPointsService(pointsString, 56, this.width, this.height);
    }
}
SkeletonImageComponent.decorators = [
    { type: Component, args: [{
                selector: 'skeleton-image',
                host: {
                    class: 'skeleton-image',
                    '[class.skeleton-effect-fade]': 'effect === "fade"',
                    '[class.skeleton-effect-pulse]': 'effect === "pulse"',
                    '[class.skeleton-effect-wave]': 'effect === "blink" || effect === "wave"',
                },
                template: `<svg
      xmlns="http://www.w3.org/2000/svg"
      [attr.width]="width"
      [attr.height]="height"
      [attr.viewBox]="'0 0 ' + width + ' ' + height"
      [style.border-radius]="borderRadius"
      preserveAspectRatio="none"
    >
      <polygon
        [style.fill]="color"
        fillRule="evenodd"
        [attr.points]="
          '0 0 ' + width + ' 0 ' + width + ' ' + height + ' 0 ' + height
        "
      />
      <path
        *ngIf="showIcon"
        [style.fill]="iconColor"
        [attr.d]="
          multiplyPoints(
            'M7.7148,49.5742 L48.2852,49.5742 C53.1836,49.5742 55.6446,47.1367 55.6446,42.3086 L55.6446,13.6914 C55.6446,8.8633 53.1836,6.4258 48.2852,6.4258 L7.7148,6.4258 C2.8398,6.4258 0.3554,8.8398 0.3554,13.6914 L0.3554,42.3086 C0.3554,47.1602 2.8398,49.5742 7.7148,49.5742 Z M39.2851,27.9414 C38.2304,27.0039 37.0351,26.5118 35.7695,26.5118 C34.457,26.5118 33.3085,26.9571 32.2304,27.918 L21.6366,37.3867 L17.3007,33.4492 C16.3163,32.582 15.2617,32.1133 14.1366,32.1133 C13.1054,32.1133 12.0976,32.5586 11.1366,33.4258 L4.1288,39.7305 L4.1288,13.8789 C4.1288,11.4414 5.4413,10.1992 7.7851,10.1992 L48.2147,10.1992 C50.535,10.1992 51.8708,11.4414 51.8708,13.8789 L51.8708,39.7539 L39.2851,27.9414 Z M17.8163,28.1992 C20.8398,28.1992 23.3241,25.7149 23.3241,22.668 C23.3241,19.6445 20.8398,17.1367 17.8163,17.1367 C14.7695,17.1367 12.2851,19.6445 12.2851,22.668 C12.2851,25.7149 14.7695,28.1992 17.8163,28.1992 Z'
          )
        "
      />
    </svg>
    <ng-content></ng-content>`
            },] }
];
SkeletonImageComponent.propDecorators = {
    width: [{ type: Input }],
    height: [{ type: Input }],
    color: [{ type: Input }],
    showIcon: [{ type: Input }],
    iconColor: [{ type: Input }],
    effect: [{ type: Input }],
    borderRadius: [{ type: Input }]
};
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoic2tlbGV0b24taW1hZ2UuanMiLCJzb3VyY2VSb290IjoiL1VzZXJzL3ZsYWRpbWlya2hhcmxhbXBpZGkvR2l0SHViL3NrZWxldG9uLWVsZW1lbnRzL3NyYy9hbmd1bGFyLyIsInNvdXJjZXMiOlsibGliL3NrZWxldG9uLWltYWdlLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUFBLE9BQU8sRUFBRSxTQUFTLEVBQUUsS0FBSyxFQUFFLE1BQU0sZUFBZSxDQUFDO0FBRWpELE9BQU8sRUFBRSx3QkFBd0IsRUFBRSxNQUFNLHVCQUF1QixDQUFDO0FBb0NqRSxNQUFNLE9BQU8sc0JBQXNCO0lBbkNuQztRQW9DVyxVQUFLLEdBQVcsSUFBSSxDQUFDO1FBQ3JCLFdBQU0sR0FBVyxHQUFHLENBQUM7UUFFckIsYUFBUSxHQUFZLElBQUksQ0FBQztJQVFwQyxDQUFDO0lBSEMsY0FBYyxDQUFDLFlBQVk7UUFDekIsT0FBTyx3QkFBd0IsQ0FBQyxZQUFZLEVBQUUsRUFBRSxFQUFFLElBQUksQ0FBQyxLQUFLLEVBQUUsSUFBSSxDQUFDLE1BQU0sQ0FBQyxDQUFDO0lBQzdFLENBQUM7OztZQTlDRixTQUFTLFNBQUM7Z0JBQ1QsUUFBUSxFQUFFLGdCQUFnQjtnQkFDMUIsSUFBSSxFQUFFO29CQUNKLEtBQUssRUFBRSxnQkFBZ0I7b0JBQ3ZCLDhCQUE4QixFQUFFLG1CQUFtQjtvQkFDbkQsK0JBQStCLEVBQUUsb0JBQW9CO29CQUNyRCw4QkFBOEIsRUFBRSx5Q0FBeUM7aUJBQzFFO2dCQUNELFFBQVEsRUFBRTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs4QkF5QmtCO2FBQzdCOzs7b0JBRUUsS0FBSztxQkFDTCxLQUFLO29CQUNMLEtBQUs7dUJBQ0wsS0FBSzt3QkFDTCxLQUFLO3FCQUNMLEtBQUs7MkJBQ0wsS0FBSyIsInNvdXJjZXNDb250ZW50IjpbImltcG9ydCB7IENvbXBvbmVudCwgSW5wdXQgfSBmcm9tICdAYW5ndWxhci9jb3JlJztcbmltcG9ydCB7IFNrZWxldG9uRWZmZWN0cyB9IGZyb20gJy4vc2tlbGV0b25FZmZlY3QnO1xuaW1wb3J0IHsgbXVsdGlwbHlTdmdQb2ludHNTZXJ2aWNlIH0gZnJvbSAnLi9tdWx0aXBseS1zdmctcG9pbnRzJztcbkBDb21wb25lbnQoe1xuICBzZWxlY3RvcjogJ3NrZWxldG9uLWltYWdlJyxcbiAgaG9zdDoge1xuICAgIGNsYXNzOiAnc2tlbGV0b24taW1hZ2UnLFxuICAgICdbY2xhc3Muc2tlbGV0b24tZWZmZWN0LWZhZGVdJzogJ2VmZmVjdCA9PT0gXCJmYWRlXCInLFxuICAgICdbY2xhc3Muc2tlbGV0b24tZWZmZWN0LXB1bHNlXSc6ICdlZmZlY3QgPT09IFwicHVsc2VcIicsXG4gICAgJ1tjbGFzcy5za2VsZXRvbi1lZmZlY3Qtd2F2ZV0nOiAnZWZmZWN0ID09PSBcImJsaW5rXCIgfHwgZWZmZWN0ID09PSBcIndhdmVcIicsXG4gIH0sXG4gIHRlbXBsYXRlOiBgPHN2Z1xuICAgICAgeG1sbnM9XCJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2Z1wiXG4gICAgICBbYXR0ci53aWR0aF09XCJ3aWR0aFwiXG4gICAgICBbYXR0ci5oZWlnaHRdPVwiaGVpZ2h0XCJcbiAgICAgIFthdHRyLnZpZXdCb3hdPVwiJzAgMCAnICsgd2lkdGggKyAnICcgKyBoZWlnaHRcIlxuICAgICAgW3N0eWxlLmJvcmRlci1yYWRpdXNdPVwiYm9yZGVyUmFkaXVzXCJcbiAgICAgIHByZXNlcnZlQXNwZWN0UmF0aW89XCJub25lXCJcbiAgICA+XG4gICAgICA8cG9seWdvblxuICAgICAgICBbc3R5bGUuZmlsbF09XCJjb2xvclwiXG4gICAgICAgIGZpbGxSdWxlPVwiZXZlbm9kZFwiXG4gICAgICAgIFthdHRyLnBvaW50c109XCJcbiAgICAgICAgICAnMCAwICcgKyB3aWR0aCArICcgMCAnICsgd2lkdGggKyAnICcgKyBoZWlnaHQgKyAnIDAgJyArIGhlaWdodFxuICAgICAgICBcIlxuICAgICAgLz5cbiAgICAgIDxwYXRoXG4gICAgICAgICpuZ0lmPVwic2hvd0ljb25cIlxuICAgICAgICBbc3R5bGUuZmlsbF09XCJpY29uQ29sb3JcIlxuICAgICAgICBbYXR0ci5kXT1cIlxuICAgICAgICAgIG11bHRpcGx5UG9pbnRzKFxuICAgICAgICAgICAgJ003LjcxNDgsNDkuNTc0MiBMNDguMjg1Miw0OS41NzQyIEM1My4xODM2LDQ5LjU3NDIgNTUuNjQ0Niw0Ny4xMzY3IDU1LjY0NDYsNDIuMzA4NiBMNTUuNjQ0NiwxMy42OTE0IEM1NS42NDQ2LDguODYzMyA1My4xODM2LDYuNDI1OCA0OC4yODUyLDYuNDI1OCBMNy43MTQ4LDYuNDI1OCBDMi44Mzk4LDYuNDI1OCAwLjM1NTQsOC44Mzk4IDAuMzU1NCwxMy42OTE0IEwwLjM1NTQsNDIuMzA4NiBDMC4zNTU0LDQ3LjE2MDIgMi44Mzk4LDQ5LjU3NDIgNy43MTQ4LDQ5LjU3NDIgWiBNMzkuMjg1MSwyNy45NDE0IEMzOC4yMzA0LDI3LjAwMzkgMzcuMDM1MSwyNi41MTE4IDM1Ljc2OTUsMjYuNTExOCBDMzQuNDU3LDI2LjUxMTggMzMuMzA4NSwyNi45NTcxIDMyLjIzMDQsMjcuOTE4IEwyMS42MzY2LDM3LjM4NjcgTDE3LjMwMDcsMzMuNDQ5MiBDMTYuMzE2MywzMi41ODIgMTUuMjYxNywzMi4xMTMzIDE0LjEzNjYsMzIuMTEzMyBDMTMuMTA1NCwzMi4xMTMzIDEyLjA5NzYsMzIuNTU4NiAxMS4xMzY2LDMzLjQyNTggTDQuMTI4OCwzOS43MzA1IEw0LjEyODgsMTMuODc4OSBDNC4xMjg4LDExLjQ0MTQgNS40NDEzLDEwLjE5OTIgNy43ODUxLDEwLjE5OTIgTDQ4LjIxNDcsMTAuMTk5MiBDNTAuNTM1LDEwLjE5OTIgNTEuODcwOCwxMS40NDE0IDUxLjg3MDgsMTMuODc4OSBMNTEuODcwOCwzOS43NTM5IEwzOS4yODUxLDI3Ljk0MTQgWiBNMTcuODE2MywyOC4xOTkyIEMyMC44Mzk4LDI4LjE5OTIgMjMuMzI0MSwyNS43MTQ5IDIzLjMyNDEsMjIuNjY4IEMyMy4zMjQxLDE5LjY0NDUgMjAuODM5OCwxNy4xMzY3IDE3LjgxNjMsMTcuMTM2NyBDMTQuNzY5NSwxNy4xMzY3IDEyLjI4NTEsMTkuNjQ0NSAxMi4yODUxLDIyLjY2OCBDMTIuMjg1MSwyNS43MTQ5IDE0Ljc2OTUsMjguMTk5MiAxNy44MTYzLDI4LjE5OTIgWidcbiAgICAgICAgICApXG4gICAgICAgIFwiXG4gICAgICAvPlxuICAgIDwvc3ZnPlxuICAgIDxuZy1jb250ZW50PjwvbmctY29udGVudD5gLFxufSlcbmV4cG9ydCBjbGFzcyBTa2VsZXRvbkltYWdlQ29tcG9uZW50IHtcbiAgQElucHV0KCkgd2lkdGg6IG51bWJlciA9IDEyMDA7XG4gIEBJbnB1dCgpIGhlaWdodDogbnVtYmVyID0gNjAwO1xuICBASW5wdXQoKSBjb2xvcjogc3RyaW5nO1xuICBASW5wdXQoKSBzaG93SWNvbjogYm9vbGVhbiA9IHRydWU7XG4gIEBJbnB1dCgpIGljb25Db2xvcjogc3RyaW5nO1xuICBASW5wdXQoKSBlZmZlY3Q6IFNrZWxldG9uRWZmZWN0cztcbiAgQElucHV0KCkgYm9yZGVyUmFkaXVzOiBzdHJpbmc7XG5cbiAgbXVsdGlwbHlQb2ludHMocG9pbnRzU3RyaW5nKSB7XG4gICAgcmV0dXJuIG11bHRpcGx5U3ZnUG9pbnRzU2VydmljZShwb2ludHNTdHJpbmcsIDU2LCB0aGlzLndpZHRoLCB0aGlzLmhlaWdodCk7XG4gIH1cbn1cbiJdfQ==
